### ISSUE TITLE
ToDo before release

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-web-components#20]
- [ ] Determine deployment strategy - theme and plugin usages 
- [ ] Document component library usage for theme and plugin 
- [ ] Clean up component documentation
- [ ] CSS customs properties for size and spacing
- [ ] Document CSS custom properties and their defaults
